[package]
edition = "2018"
name = "bootloader"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = {path = "uefi"}

[[bin]]
bench = false
doc = false
doctest = false
name = "bootloader"
test = false
